openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /product/createProduct/:
    post:
      operationId: product_createProduct_create
      tags:
      - product
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateModifyProductRequest'
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetriveProduct'
              examples:
                Example1:
                  value:
                    name: Product 1
                    descreption: Description for Product 1
                    price: 100.0
                    stock: 50
                    category: Consoles
                  summary: Example 1
                  description: longer description
          description: ''
  /product/deleteProduct/{prod_id}/:
    delete:
      operationId: product_deleteProduct_destroy
      parameters:
      - in: path
        name: prod_id
        schema:
          type: integer
        required: true
      tags:
      - product
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /product/productByID/{prod_id}/:
    get:
      operationId: product_productByID_retrieve
      parameters:
      - in: path
        name: prod_id
        schema:
          type: integer
        required: true
      tags:
      - product
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetriveProduct'
          description: ''
  /product/productsByCategories/{category}/:
    get:
      operationId: product_productsByCategories_list
      parameters:
      - in: path
        name: category
        schema:
          type: string
        required: true
      tags:
      - product
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RetriveProduct'
          description: ''
  /product/updateProduct/{prod_id}/:
    put:
      operationId: product_updateProduct_update
      parameters:
      - in: path
        name: prod_id
        schema:
          type: integer
        required: true
      tags:
      - product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateModifyProductRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateModifyProductRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateModifyProductRequest'
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateModifyProduct'
          description: ''
    patch:
      operationId: product_updateProduct_partial_update
      parameters:
      - in: path
        name: prod_id
        schema:
          type: integer
        required: true
      tags:
      - product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCreateModifyProductRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCreateModifyProductRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCreateModifyProductRequest'
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateModifyProduct'
          description: ''
components:
  schemas:
    CreateModifyProduct:
      type: object
      properties:
        name:
          type: string
          default: Product 1
        descreption:
          type: string
          default: Description for Product 1
        price:
          type: number
          format: double
          default: 100.0
        stock:
          type: integer
          default: 50
        category:
          type: string
          default: Consoles
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
          readOnly: true
        main_image:
          type: string
          format: uri
      required:
      - images
    CreateModifyProductRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          default: Product 1
        descreption:
          type: string
          minLength: 1
          default: Description for Product 1
        price:
          type: number
          format: double
          default: 100.0
        stock:
          type: integer
          default: 50
        category:
          type: string
          minLength: 1
          default: Consoles
        main_image:
          type: string
          format: binary
    Image:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        photo_url:
          type: string
          readOnly: true
      required:
      - id
      - photo_url
    ImageRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
    PatchedCreateModifyProductRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          default: Product 1
        descreption:
          type: string
          minLength: 1
          default: Description for Product 1
        price:
          type: number
          format: double
          default: 100.0
        stock:
          type: integer
          default: 50
        category:
          type: string
          minLength: 1
          default: Consoles
        main_image:
          type: string
          format: binary
    RetriveProduct:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
          readOnly: true
        name:
          type: string
        descreption:
          type: string
        price:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        stock:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        category:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
          nullable: true
      required:
      - category
      - descreption
      - id
      - images
      - name
      - price
      - stock
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
